# Generated by Django 3.2.10 on 2021-12-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_tokens', '0002_locktoken_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locktoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='locktoken',
            name='locked_object_id',
            field=models.CharField(max_length=100),
        ),
    ]
